#!/bin/sh -e

# find directory enclosing the script
_self=$(
	test -d "$(dirname "$0")" && cd "$(dirname "$0")"
	test "$(dirname "$0")" = . && cd "$(dirname "$(command -v "$0")")"
	test -L "$(basename "$0")" && cd "$(dirname "$(readlink "$(basename "$0")")")"
	pwd
)

# determine machine identifier
_machine=$(
	# shellcheck disable=SC3028
	if test "$HOSTNAME" && env | grep -Fq HOSTNAME ; then
		echo "$HOSTNAME"
	elif command -v scutil > /dev/null ; then
		scutil --get LocalHostName
	else
		hostname
	fi | tr '[:upper:]' '[:lower:]'
)
_machine=${_machine%.local}

. "$_self/modules/build/utils.sh"

# check if a configuration exists
if ! test -d "$_self/machines/$_machine" ; then
	printError "No configuration for this machine: $_machine"
	exit 68  # EX_NOHOST
fi

# make sure Nix is installed
if ! nix store info > /dev/null 2>&1 ; then
	. "$_self/modules/build/state.sh"
	. "$_self/modules/nix/install.sh"
fi

# run default commands if there are no arguments
if test "$*" = '' -o "$*" = -i -o "$*" = --interactive ; then
	commands=$(nix eval --quiet --no-warn-dirty --apply toString --raw \
		"${_self}#baseConfigurations.${_machine}.config.system.defaultCommands")
	if test "$commands" ; then
		# shellcheck disable=SC2086
		set -- "$@" $commands
	else
		set -- "$@" activate
	fi
	_argv=$*
fi

# self-update flake
if checkArgs update-flake update all ; then
	trace nix flake update --flake "$_self"
fi

# update package versions
if checkArgs update-versions update all ; then
	. "$_self/modules/build/versions.sh"
	runAllUpdates
fi

# noself options skip the above two steps
if checkArgs update-noself ; then
	set -- "$@" update
fi
if checkArgs all-noself ; then
	set -- "$@" all
fi

# generate rebuild script for this machine
script=$(
	nix build --quiet --no-link --print-out-paths --no-warn-dirty \
		"${_self}#baseConfigurations.${_machine}.config.system.build.rebuild"
)

# run rebuild script
export _self _machine _helpCommandsPrinted
exec "$script" "$@"
