# run rebuild tests on Ubuntu and macOS
name: Rebuild Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        machine: [ test-darwin, test-linux, test-nosys ]
        include:
        - machine: test-darwin
          os: macos-latest
        - machine: test-linux
          os: ubuntu-latest
        - machine: test-nosys
          os: ubuntu-latest
    name: Rebuild ${{ matrix.machine }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    env:
      HOSTNAME: ${{ matrix.machine }}
      NIX_CONFIG: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run rebuild
      run: ./rebuild

    - name: Rerun rebuild
      run: |
        ! ./rebuild | grep .
        test ${PIPESTATUS[0]} -eq 0 -a ${PIPESTATUS[1]} -ne 0

    - name: Check for empty state directory
      if: ${{ matrix.machine == 'test-nosys' }}
      run: test ! -d ~/.local/state/rebuild

    - name: Run cleanup
      run: ./rebuild clean

    - name: Pre-heat store for Linux builder
      if: ${{ runner.os == 'macOS' }}
      run: ~/.local/state/nix/profile/bin/nix build --no-link nixpkgs/$(jq --raw-output .nodes.nixpkgs.locked.rev flake.lock)#darwin.linux-builder

    - name: Restart patched Nix
      if: ${{ runner.os == 'macOS' }}
      run: sudo pkill nix ; sleep 5

    - name: Check flake
      run: ~/.local/state/nix/profile/bin/nix flake check
